name: model_train
permissions:
  id-token: write
  contents: write
on:
  push:
    branches:
      - main  # Mettez ici la branche sur laquelle vous souhaitez déclencher cette action
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train model
        run: python train_model.py

      - name: Generate reports
        run: |
          echo "RF and LR Model Score" > report.md
          cat scores.txt >> report.md
          
          echo "Confusion Matrix & Feature Importance" > report1.md
          echo '![](./ConfusionMatrix.png "ConfusionMatrix")' >> report1.md
          echo '![](./FeatureImportance.png "FeatureImportance")' >> report1.md

          cat report.md report1.md > combined_file.md

      - name: Create CML comment with report
        run: |
          cml comment create combined_file.md --watch
