name: model_train
permissions:
  id-token: write
  contents: write

on:
  push:
    branches: [ main ]

jobs:

  run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: iterative/setup-cml@v1
      with:
        repo-token: ${{ toJson(idToken) }}
        
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Train model
      run: |
        python train_model.py
        
        echo "RF and LR Model Score" > report.md
        cat scores.txt >> report.md
        
        echo "Confusion Matrix & Feature Importance" > report1.md
        echo '![](./ConfusionMatrix.png "ConfusionMatrix")' >> report1.md
        echo '![](./FeatureImportance.png "FeatureImportance")' >> report1.md
        
        cat report.md report1.md > combined_file.md
        
    - name: Comment CML report
      run: cml comment create combined_file.md
