name: model_train
permissions:
  id-token: write
  contents: write
on:
  - push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
        with:
          node-version: '20'
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python train_model.py

          # Generate report
          echo "RF and LR Model Score" > report.md
          cat scores.txt >> report.md
          
          echo "Confusion Matrix & Feature Importance" > report1.md
          echo '![](./ConfusionMatrix.png "ConfusionMatrix")' >> report1.md
          echo '![](./FeatureImportace.png "FeatureImportace")' >> report1.md

          cat report.md report1.md > combined_file.md

          # Create CML comment with images inline
          cml comment create combined_file.md --publish ConfusionMatrix.png --publish FeatureImportace.png
