name: model_train
permissions:
  id-token: write
  contents: write
on:
  - push
jobs:
  run:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
        with:
          node-version: '20'
      - uses: actions/checkout@v3
      - name: train model
        env: 
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          pip install -r requirements.txt
          python train_model.py

          echo "RF and LR Model Score" > report.md
          cat scores.txt >> report.md
          
          echo "Confusion Matrix & Feature Importance" > report1.md
          
          # Publier les images et ajouter les URLs générées dans report1.md
          CM_URL=$(cml-publish ConfusionMatrix.png --md)
          FI_URL=$(cml-publish FeatureImportance.png --md)
          
          echo "$CM_URL" >> report1.md
          echo "$FI_URL" >> report1.md

          # Combiner les fichiers report.md et report1.md
          cat report.md report1.md > combined_file.md
          
          # Créer le commentaire CML
          cml comment create combined_file.md
